version: "3"

services:
  backend-apis:
    image: inderjeet5533/curd_demo:latest
    ports:
      - 8080:8080
  frontend:
    image: inderjeet5533/curd_demo_reactjs:latest
    ports:
      - 5173:5173
    depends_on:
      - backend-apis
